site_name: Nishikoh.io
site_author: Nishikoh
docs_dir: blog
site_url: https://nishikoh.github.io/

theme:
  language: "ja"
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.code.annotate
    # - navigation.instant # blogging と併用はできない
    - navigation.top

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: true
  search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  # extra:
  #   search:
  #     language: "ja"
  font:
    text: Zen Maru Gothic
    code: Roboto Mono
  icon:
    logo: logo

plugins:
  - monorepo
  - git-revision-date-localized:
      type: iso_datetime
  - search:
      lang:
        - ja
        - en
  # 検索インデックスの単語区切り文字設定
  # separator: '[\s\-\.]+'
  - blogging:
      locale: ja
      # GLOBAL CATEGORY: configs for {{ blog_content }}
      dirs:
        - ./
  - tags:
      tags_file: tags.md
  - exclude:
      glob:
        - "slidev/*"
        - "node_modules/*"
        - "**/.git/*"
        - "**/node_modules/*"

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nishikoh
    - icon: fontawesome/solid/blog
      link: https://zenn.dev/nishikoh
  search:
    language: "ja"

# https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
