site_name: Nishikoh.io
site_author: Nishikoh
docs_dir: blog
site_url: https://nishikoh.github.io/

theme:
  language: "ja"
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.code.annotate
    - navigation.instant # blogging paging と併用はできない
    - navigation.top
    - navigation.tracking
    - toc.follow

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: true
  search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  # extra:
  #   search:
  #     language: "ja"
  font:
    text: Zen Antique
    code: Roboto Mono
  icon:
    logo: logo

plugins:
  - monorepo
  - git-revision-date-localized:
      type: iso_datetime
  - search:
      lang:
        - ja
        - en
  # 検索インデックスの単語区切り文字設定
  # separator: '[\s\-\.]+'
  - blogging:
      locale: ja
      # GLOBAL CATEGORY: configs for {{ blog_content }}
      dirs:
        - ./
      size: 1000 # 大きな値にしないと2回繰り返して表示される
      features:
        tags: {}
      sort: 
        from: new        # Sort from new to old, default
        # or old         # Sort from old to new
        by: creation     # Sort by the first commit time, default
        # or revision    # Sort by the latest commit time
      full_content: false # Use the full content for blog description
      paging: false # trueにするとnavigation.instantと競合する
      show_total: true
      theme:
        name: card
  - tags:
      tags_file: tags.md
  - exclude:
      glob:
        - "slidev/*"
        - "node_modules/*"
        - "**/.git/*"
        - "**/node_modules/*"
        # - "private/*"
  - macros:
      render_by_default: true
      on_error_fail: true
      verbose: true


extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nishikoh
    - icon: fontawesome/solid/blog
      link: https://zenn.dev/nishikoh
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/koki-nishihara/
  generator: false

  search:
    language: "ja"

extra_css:
  - https://www.neoteroi.dev/mkdocs-plugins/css/neoteroi.css # https://github.com/Neoteroi/mkdocs-plugins/issues/30

# https://squidfunk.github.io/mkdocs-material/reference/
# https://facelessuser.github.io/pymdown-extensions/extensions/arithmatex/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true
  - neoteroi.timeline
  - neoteroi.cards

