site_name: Nishikoh.io
theme:
  language: "ja"
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tabs.sticky
    - search.suggest
    - search.highlight
    - content.code.annotate
    - navigation.instant

  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

  # 404 page
  # static_templates:
  #   - 404.html

  # Necessary for search to work properly
  # include_search_page: true
  # search_index_only: false

  # Default values, taken from mkdocs_theme.yml
  # extra:
  #   search:
  #     language: "ja"
  font:
    text: Zen Maru Gothic
    code: Roboto Mono
  icon:
    logo: logo
plugins:
  - monorepo
  - search:
      lang:
        - ja
        - en
  # 検索インデックスの単語区切り文字設定
  # separator: '[\s\-\.]+'
  - tags
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Nishikoh
  search:
    language: "ja"
# https://squidfunk.github.io/mkdocs-material/reference/
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - footnotes
  - footnotes
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
