site_name: Nishikoh.io
theme:
  name: material
  palette:
    scheme: slate
    primary: teal

  # 404 page
  static_templates:
    - 404.html

  # Necessary for search to work properly
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: ja
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
plugins:
  - monorepo
