name: GitHub Pages

on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: "pages"
  cancel-in-progress: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: ssh setting
        env:
          TOKEN: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p $HOME/.ssh/
          echo -e "$TOKEN" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
      - name: Checkout
        shell: bash
        run: git submodule update --init --force --recursive

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install dependencies
        run: pip install -r ./requirements.txt

      - name: delete private
        run: rm -rf blog/private blog/node_modules

      - name: Build
        run: ENABLE=true mkdocs build
        env:
          ANALYTICS_PROPERTY: ${{ secrets.ANALYTICS_PROPERTY }}
          GOOGLE_SITE_VERIFICATION: ${{ secrets.GOOGLE_SITE_VERIFICATION }}
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

      - uses: geekyeggo/delete-artifact@v5
        with:
          name: github-pages
